---
- hosts: tag_Version_6_3_1
  become: true
  vars:
    currentVersion: 6.3.1
    version: 6.3.2
    date: ansible_date_time
  roles:
    - change-version
  tasks:
    - name: remove x from updates in motd
      file: path=/etc/update-motd.d/70-available-updates mode=0644
      notify: update-motd

    - name: remove x from system updates in motd  
      file: path=/etc/update-motd.d/75-system-update mode=0644
      notify: update-motd

    - name: disable yum updates
      lineinfile: dest=/etc/yum.conf insertafter="deltarpm=0" line="exclude=*"

    - name: replace lemp script with 2.0
      template: src=templates/lemp.sh.j2 dest=/home/ec2-user/.bin/lemp.sh

    - name: add nginx and php only script
      template: src=templates/nginxphp.sh.j2 dest=/home/ec2-user/.bin/nginxphp.sh

    - name: add nginx php script to aliases
      lineinfile: dest=/home/ec2-user/.bashrc line="alias np='./home/ec2-user/.bin/nginxphp.sh'"

    - name: download adminer
      get_url:
        url: https://adminer.org/latest-mysql-en.php
        dest: /var/www/html/

    - name: change name of adminer
      command: mv /var/www/html/adminer-4.2.5-mysql-en.php /var/www/html/blondebimbos.php

    - name: change owner of adminer to nginx
      file:
        path=/var/www/html/blondebimbos.php
        owner=nginx
        group=nginx
      ignore_errors: True

    - name: remove phpMyAdmin
      yum:
        name=phpMyAdmin
        state=absent

    - name: remove pma link
      file: 
        path=/var/www/html/phpMyAdmin
        state=absent


    - name: update security packages
      command: yum update --security
