---
- hosts: tag_Version_6_3
  become: true
  vars:
    currentVersion: 6.3
    version: 6.3.1
    date: ansible_date_time
  tasks:
    - name: upgrade all packages
      yum: name=* state=latest

    - stat: path=/etc/pki/nginx/dhparams.pem
      register: dh 
    - name: create directory
      file: path=/etc/pki/nginx state=directory mode=0755
      when: dh.stat.exists == False     
    - name: create dhparam file  
      file: path=/etc/pki/nginx/dhparams.pem state=touch owner=root group=root mode=0644 
      when: dh.stat.exists == False
    - name: run dhparam command
      command: openssl dhparam -out /etc/pki/nginx/dhparams.pem 2048

      
    - stat: path=/etc/nginx/nginx.conf.{{currentVersion}}
      register: nx

    - name: copy old nginx.conf file
      command: mv /etc/nginx/nginx.conf /etc/nginx/nginx.conf.{{currentVersion}}
      when: nx.stat.exists == False


    - stat: path=/etc/nginx/nginx.conf
      register: nxc

    - name: grab nginx.conf template
      template: src=templates/6.3.1.nginx.conf.j2 
                dest=/etc/nginx/nginx.conf    
      notify: "restart nginx"
      when: nxc.stat.exists == False


    - name: Fix permissions for phpMyAdmin
      file: path=/var/lib/php/5.6/session
            owner=nginx
            group=nginx
      notify: "restart php"


  roles:
    - change-version

  handlers:
    - name: restart nginx
      service: name=nginx state=restarted

    - name: restart mysqld
      service: name=mysqld state=restarted

    - name: restart php
      service: name=php-fpm-5.6 state=restarted

