---
- hosts: tag_Version_6_3_1
  become: true
  vars:
    currentVersion: 6.3.1
    version: 6.3.2
    date: ansible_date_time
  roles:
    - change-version
  tasks:
    - name: remove x from updates in motd
      file: path=/etc/update-motd.d/70-available-updates mode=0644
      notify: update-motd

    - name: remove x from system updates in motd  
      file: path=/etc/update-motd.d/75-system-update mode=0644
      notify: update-motd



