---
- hosts: tag_Name_BMG
  become: true
  vars:
    currentVersion: 6.3.4
    version: 6.4
  roles:
    - php70
    - change-version
  tasks:
    - name: move over new lemp script
      copy: src=templates/lemp.sh dest=/home/ec2-user/.bin/lemp.sh

    - name: move over adminer script
      copy: src=templates/ad-down.sh dest=/home/ec2-user/.bin/ad-down.sh owner=ec2-user group=ec2-user mode=0755

    - name: copy get_wp.sh over to .bin
      command: mv /home/ec2-user/get_wp.sh /home/ec2-user/.bin/get_wp.sh

    - name: fix adminer issue
      file: path=/var/lib/php state=directory recurse=yes owner=nginx group=nginx

    - name: fix /var/www/html
      file: path=/var/www/html state=directory recurse=yes owner=nginx group=nginx

