---
- hosts: tag_Version_6_4
  become: true
  vars:
    currentVersion: 6.4
    version: 6.5
  vars_prompt:
    - name: 'mysqlpass'
      prompt: 'enter password for mysql'
      private: yes
  roles:
    - mysql56
    - nginx_6.5
    - change-version
  tasks:
    #    - name: move over new np script
    #      copy: src=templates/np.sh dest=/home/ec2-user/.bin/np.sh
    #
    #    - name: move over adminer script
    #      copy: src=templates/ad-down.sh dest=/home/ec2-user/.bin/ad-down.sh owner=ec2-user group=ec2-user mode=0755
    #
    #
    #    - name: add line to php.ini
    #
    #
