---



- name: Adding http2 to site1.conf
  lineinfile: dest=/etc/nginx/sites/site1.conf regexp='^     listen                    *:443 ssl;' line='     listen                    *:443 ssl http2;' 
  when: ec2_tag_SSL == 'True'
  notify: restart nginx

- name: Adding http2 to site2.conf
  lineinfile: dest=/etc/nginx/sites/site2.conf regexp='^     listen                    *:443 ssl;' line='     listen                    *:443 ssl http2;' 
  when: ec2_tag_SSL == 'True'
  notify: restart nginx
  
- name: Adding http2 to site1.conf.disabled regexp='^     listen                    *:443 ssl;' line='     listen                    *:443 ssl http2;' 
  lineinfile: dest=/etc/nginx/sites/site1.conf.disabled
  when: ec2_tag_SSL == 'False' or ec2_tag_SSL == 'Redirect'
  notify: restart nginx
  


- name: Adding http2 to site1.conf
  lineinfile: dest=/etc/nginx/sites/site1.conf regexp='^      listen                    [::]:443 ssl http2;' line='      listen                    [::]:443 ssl http2;'
  when: ec2_tag_SSL == 'True'
  notify: restart nginx
  
- name: Adding http2 to site2.conf
  lineinfile: dest=/etc/nginx/sites/site2.conf regexp='^      listen                    [::]:443 ssl http2;' line='      listen                    [::]:443 ssl http2;'
  when: ec2_tag_SSL == 'True'
  notify: restart nginx
  
- name: Adding http2 to site1.conf.disabled regexp='^      listen                    [::]:443 ssl http2;' line='      listen                    [::]:443 ssl http2;' 
  lineinfile: dest=/etc/nginx/sites/site1.conf.disabled
  when: ec2_tag_SSL == 'False' or ec2_tag_SSL == 'Redirect'
  notify: restart nginx
  





 
