---
- name: change MOTD to {{version}}
  lineinfile: dest=/etc/update-motd.d/30-banner
              regexp='Nginx [Bb]ox'
              line="                      Nginx Box {{version}}"
  notify: update-motd

- name: change  ec2 tag to {{version}}
  ec2_tag:
    tags:
      Version == {{version}}
  register: ec2_tags}


#- name: get ec2 facts
#  action: ec2_facts
#
#
#- name: Change Version Tag to {{version}}
#  ec2_tag:
#    region:  us-west-2
#    resource: "{{ ansible_ec2_instance_id }}"
#    state: present
#    tags:
#      Version: "{{version}}"
#  register: ec2_tags
