---


  # Update Nginx

- name: enable yum updates
  lineinfile: 
    dest=/etc/yum.conf 
    state=absent 
    line="exclude=*"

- name: update nginx
  yum:
    name: nginx
    state: latest

- name: update security packages
  command: yum update -y --security
  ignore_errors: yes

- name: disable yum updates
  lineinfile: dest=/etc/yum.conf insertafter="deltarpm=0" line="exclude=*"

- name: remove comment from nginx.conf geoip module load
  lineinfile: dest=/etc/nginx/nginx.conf regexp='^#load_module "/usr/lib64/nginx/modules/ngx_http_geoip_module.so";' line='load_module "/usr/lib64/nginx/modules/ngx_http_geoip_module.so";'



  # Move over extra files

- name: move over fastcgi template
  template: src=roles/nginx_6.3.4/templates/fastcgi.conf.j2 dest=/etc/nginx/global/fastcgi.conf

- name: add non-ssl conf to ssl sites
  template: src=roles/nginx_6.3.4/templates/site.non-ssl.conf.j2 dest=/etc/nginx/sites/site.non-ssl.conf.disabled
  when: ec2_tag_SSL == 'True' or  ec2_tag_SSL == 'Redirect'


- name: add non-ssl redirect conf to ssl sites
  template: src=roles/nginx_6.3.4/templates/site.non-ssl.redirect.conf.j2 dest=/etc/nginx/sites/site.non-ssl.redirect.conf.disabled
  when: ec2_tag_SSL == 'True' or  ec2_tag_SSL == 'False'



  # New site1.conf template file with correct sub

- name: new site.conf
  template: src=roles/nginx_6.3.4/templates/site1.conf.j2 dest=/etc/nginx/sites/site1.conf
  when: ec2_tag_SSL == 'True'

- name: new site.non-ssl.conf
  template: src=roles/nginx_6.3.4/templates/site.non-ssl.conf.j2 dest=/etc/nginx/sites/site.non-ssl.conf
  when: ec2_tag_SSL == 'False'

- name: new site.non-ssl.redirect.conf
  template: src=roles/nginx_6.3.4/templates/site.non-ssl.redirect.conf.j2 dest=/etc/nginx/sites/site.non-ssl.redirect.conf
  when: ec2_tag_SSL == 'Redirect'




 
